export const IPC_CHANNELS = {
  CODE_EXECUTE: 'code/execute',
  PACKAGE_INSTALL: 'package/install',
  PACKAGE_UNINSTALL: 'package/uninstall',
  ENV_INFO: 'env/info',
  APP_MINIMIZE: 'app/minimize',
  APP_MAXIMIZE: 'app/maximize',
  APP_CLOSE: 'app/close',
  APP_VERSION: 'app/version',
  AUTH_CLERK_TOKEN: 'auth:clerk-token',
  AUTH_CLERK_TOKEN_GET: 'auth:clerk-token:get',
  AUTH_CLERK_LOGOUT: 'auth:clerk-logout',
  AUTH_OPEN_SIGN_IN: 'auth/open-sign-in',
  AUTH_FETCH_ENTITLEMENTS: 'auth/fetch-entitlements',
  AUTH_REQUEST_SIGN_IN_TOKEN: 'auth/request-sign-in-token',
  AUTH_OAUTH_COMPLETE: 'auth/oauth-complete',
  AUTH_TOKEN_REFRESHED: 'auth:token-refreshed',
  TOGGLE_TITLEBAR: 'toggle-titlebar',
  UPDATE_AVAILABLE: 'update/available',
  UPDATE_DOWNLOADED: 'update/downloaded',
  UPDATE_INSTALL: 'update/install',
} as const;
